/*
crear una receta nueva
{
"name": Canasta de frutas y verduras

"image":
http://st.gdefon.com/wallpapers_original/wallpapers/405159_korziny_ovoshhi_frukty_xleb_pomidory_perec_shampin_7644x5000_(www.GdeFon.ru).jpg

"summary":
 La anterior es una imgen de ejemplo, en este campo iria un resumen de la receta en si, como veran, este texto es de relleno para poder visualizar mejor las funcionalidades de la app. 

"stepByStep":
"1": Consiga frutas y verduras de su huerto o verduleria mas cercana.
"2": Consiga una canasta de mimbre y botellas con liquido para realizar una buena toma.
"3": Recuerde, la comida entra primero por los ojos.

SQL ====>
DELETE FROM recipes; ELIMINA TODOS LOS DATOS CREADOS EN LA BDD
  */