/*
crear una receta nueva
{
    "name": "Facundo",
    "image" : "www.google.jpg",
    "summaryOfTheDish": "sarasa",
    "levelOfHealthyEating": 55,
    "stepByStep": ["sarasa1", "sarasa2", "sarasa3"]
}

// https://api.spoonacular.com/recipes/22/information?apiKey=a4646e35136d4383903a52e05624e079
// RECETAS POR ID

// https://api.spoonacular.com/recipes/complexSearch?apiKey=a4646e35136d4383903a52e05624e079&number=10&addRecipeInformation=true
// TODAS LAS RECETAS

SQL ====>
DELETE FROM recipes; ELIMINA TODOS LOS DATOS CREADOS EN LA BDD
  */