const GET_RECIPES = "GET_RECIPES"
const GET_RECIPE = "GET_RECIPE"
const CLEAN_DETAIL_RECIPE = "CLEAN_DETAIL_RECIPE"
const GET_DIETS = "GET_DIETS"
const GET_SEARCH_NAME = "GET_SEARCH_NAME"
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const ORDER_BY_SCORE = 'ORDER_BY_SCORE';
const FILTER_BY_DIET = 'FILTER_BY_DIET';
const FILTER_DB_OR_API = 'FILTER_DB_OR_API';
const SUBMIT_RECIPE = "SUBMIT_RECIPE";
const RESET_FILTERS = "RESET_FILTERS"

export {GET_RECIPE,
        GET_RECIPES,
        CLEAN_DETAIL_RECIPE,
        GET_DIETS,
        GET_SEARCH_NAME,
        ORDER_BY_NAME,
        ORDER_BY_SCORE,
        FILTER_BY_DIET,
        FILTER_DB_OR_API,
        SUBMIT_RECIPE,
        RESET_FILTERS
    }